#include "src/game/envfx_snow.h"

const GeoLayout segasonic_Eyes_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Half_Closed_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Eyes_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Closed_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Eyes_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Right_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Eyes_Left[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Left_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Eyes_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Up_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Eyes_Down[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Down_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Eyes_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Dead_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Mouth_Happy[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Mouth_Happy_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Mouth_Shocked[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Mouth_Shocked_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Mouth_Surprised[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Mouth_Surprised_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Mouth_No_Emotion[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Mouth_No_Emotion_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Side_Mouth_DL_mesh_layer_1_mat_override_Mouth_Frown__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Side_Mouth_DL_mesh_layer_1_mat_override_Mouth_Smile__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Side_Mouth_DL_mesh_layer_1_mat_override_Mouth_Grin__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Side_Mouth_DL_mesh_layer_1_mat_override_Mouth_Attacked__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Mouth_Switch[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_mouth),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Side_Mouth_DL_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt1),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt2),
			GEO_BRANCH(1, segasonic_Mouth_Happy),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt4),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt5),
			GEO_BRANCH(1, segasonic_Mouth_Shocked),
			GEO_BRANCH(1, segasonic_Mouth_Surprised),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Left_Hand_Thumbs_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, -78, 0, 0, segasonic_Left_Hand_Thumbs_Up_Switch_Option_Left_Hand_Thumbs_Up_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, segasonic_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, segasonic_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, segasonic_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Left_Sock[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Left_Sock_Switch_Option_Left_Sock_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Right_Sock[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(2, geo_mario_hand_foot_scaler),
		GEO_SCALE(LAYER_OPAQUE, 65536),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Right_Sock_Switch_Option_Right_Sock_DL_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Spin[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Spin_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, segasonic_Switch_Option_Spin_mesh_layer_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Ball[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Ball_mesh_layer_1),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash1_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash4_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash5_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash6_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash7_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Spin_Dash[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_SWITCH_CASE(0, geo_custom_spindash_states),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Spin_Dash_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt1),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt2),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt3),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt4),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt5),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt6),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt3_Switch_States_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_Insta_Shield[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_DISPLAY_LIST(LAYER_ALPHA, segasonic_Switch_Option_Insta_Shield_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Insta_Shield_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Half_Closed_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Closed_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Right_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Left[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Left_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Up_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Down[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Down_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Dead_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Happy[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_Happy_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Shocked[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_Shocked_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Surprised[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_Surprised_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_No_Emotion[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_No_Emotion_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Happy[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_Happy_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Shocked[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_Shocked_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Surprised[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_Surprised_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Side_Mouth_DL_mesh_layer_1_mat_override_Mouth_Frown__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Side_Mouth_DL_mesh_layer_1_mat_override_Mouth_Smile__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Side_Mouth_DL_mesh_layer_1_mat_override_Mouth_Grin__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Side_Mouth_DL_mesh_layer_1_mat_override_Mouth_Attacked__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Switch[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_mouth),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Side_Mouth_DL_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt1),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt2),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Happy),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt4),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt1_Switch_Mouth_States_opt5),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Shocked),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Surprised),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Left_Hand_Thumbs_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, -78, 0, 0, segasonic_Left_Hand_Thumbs_Up_Switch_Option_Left_Hand_Thumbs_Up_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Left_Sock[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Sock_Switch_Option_Left_Sock_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Right_Sock[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(2, geo_mario_hand_foot_scaler),
		GEO_SCALE(LAYER_OPAQUE, 65536),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Sock_Switch_Option_Right_Sock_DL_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Spin[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Spin_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Spin_mesh_layer_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Ball[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Ball_mesh_layer_1),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash1_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash4_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash5_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash6_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_SpinDash7_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Spin_Dash[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_SWITCH_CASE(0, geo_custom_spindash_states),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Spin_Dash_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt1),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt2),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt3),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt4),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt5),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt6),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt3_Switch_States_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Insta_Shield[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Insta_Shield_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Insta_Shield_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Mouth_Neutral_DL_mesh_layer_1_mat_override_Mouth_Frown__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Mouth_Neutral_DL_mesh_layer_1_mat_override_Mouth_Smile__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Mouth_Neutral_DL_mesh_layer_1_mat_override_Mouth_Grin__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Mouth_Neutral_DL_mesh_layer_1_mat_override_Mouth_Attacked__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_ball_switch),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 40, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 62, 0, 0, segasonic_Torso_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 61, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Eyes_Centered_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Half_Closed),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Closed),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Right),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Left),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Up),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Down),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Eyes_Dead),
										GEO_CLOSE_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_mouth_side),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_mouth),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Mouth_Neutral_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt1),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt2),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Happy),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt4),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt5),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Shocked),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Surprised),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_No_Emotion),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Mouth_Switch),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 60, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, segasonic_Left_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Forearm_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Left_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_custom_hand_switch),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Left_Hand_Open),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Left_Hand_Thumbs_Up),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, -60, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, segasonic_Right_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Forearm_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Right_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_custom_hand_switch),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Right_Hand_Open),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Right_Hand_Peace),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Right_Hand_Cap),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Right_Hand_Wing_Cap),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 0, 30, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, segasonic_Left_Thigh_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Leg_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, segasonic_Left_Leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Shoe_DL_mesh_layer_1),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Shoe_DL_mesh_layer_2),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Left_Sock),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 67, 50, 46, -19, 7, 159),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Wing_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 0, -30, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, segasonic_Right_Thigh_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Leg_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, segasonic_Right_Leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ASM(2, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Shoe_DL_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Shoe_DL_mesh_layer_2),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Right_Sock),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 67, 50, -46, 19, -7, 159),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Wing_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Spin),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Ball),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Spin_Dash),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_segasonic_Insta_Shield),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Half_Closed_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Closed_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Right_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Left[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Left_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Up_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Down[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Down_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Eyes_Dead_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Happy[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Mouth_Happy_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Shocked[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Mouth_Shocked_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Surprised[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Mouth_Surprised_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_No_Emotion[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Mouth_No_Emotion_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Happy[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Mouth_Happy_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Shocked[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Mouth_Shocked_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Surprised[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Mouth_Surprised_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Switch[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_mouth),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Side_Mouth_DL_mesh_layer_1_mat_override_Metal__CAP__0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Happy),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Shocked),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Surprised),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Left_Hand_Thumbs_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, -78, 0, 0, segasonic_Left_Hand_Thumbs_Up_Switch_Option_Left_Hand_Thumbs_Up_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__CAP__0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal__CAP__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, segasonic_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_2_mat_override_Metal__CAP__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal__CAP__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, segasonic_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_4_mat_override_Metal__CAP__0),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, segasonic_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_2_mat_override_Metal__CAP__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Left_Sock[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Left_Sock_Switch_Option_Left_Sock_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Right_Sock[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(2, geo_mario_hand_foot_scaler),
		GEO_SCALE(LAYER_OPAQUE, 65536),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Right_Sock_Switch_Option_Right_Sock_DL_mesh_layer_1_mat_override_Metal__CAP__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Spin[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Spin_mesh_layer_1_mat_override_Metal__CAP__0),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, segasonic_Switch_Option_Spin_mesh_layer_2_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Ball[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Ball_mesh_layer_1_mat_override_Metal__CAP__0),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Spin_Dash[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_SWITCH_CASE(0, geo_custom_spindash_states),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_Metal__CAP__0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Insta_Shield[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_DISPLAY_LIST(LAYER_ALPHA, segasonic_Switch_Option_Insta_Shield_mesh_layer_4_mat_override_Metal__CAP__0),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Switch_Option_Insta_Shield_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_ball_switch),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 40, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 62, 0, 0, segasonic_Torso_mesh_layer_1_mat_override_Metal__CAP__0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 61, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Eyes_Centered_DL_mesh_layer_1_mat_override_Metal__CAP__0),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Half_Closed),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Closed),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Right),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Left),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Up),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Down),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Eyes_Dead),
										GEO_CLOSE_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_mouth_side),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_mouth),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Mouth_Neutral_DL_mesh_layer_1_mat_override_Metal__CAP__0),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Happy),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Shocked),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Surprised),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_No_Emotion),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Mouth_Switch),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 60, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, segasonic_Left_Arm_Color_mesh_layer_1_mat_override_Metal__CAP__0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Left_Forearm_skinned_mesh_layer_1_mat_override_Metal__CAP__0),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Left_Forearm_mesh_layer_1_mat_override_Metal__CAP__0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_custom_hand_switch),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Left_Hand_DL_mesh_layer_1_mat_override_Metal__CAP__0),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Left_Hand_Open),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Left_Hand_Thumbs_Up),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, -60, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, segasonic_Right_Arm_Color_mesh_layer_1_mat_override_Metal__CAP__0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Right_Forearm_skinned_mesh_layer_1_mat_override_Metal__CAP__0),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Right_Forearm_mesh_layer_1_mat_override_Metal__CAP__0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_custom_hand_switch),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Right_Hand_DL_mesh_layer_1_mat_override_Metal__CAP__0),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Right_Hand_Open),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Right_Hand_Peace),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Right_Hand_Cap),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Right_Hand_Wing_Cap),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 0, 30, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, segasonic_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__CAP__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Left_Leg_skinned_mesh_layer_1_mat_override_Metal__CAP__0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, segasonic_Left_Leg_mesh_layer_1_mat_override_Metal__CAP__0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Left_Shoe_DL_mesh_layer_1_mat_override_Metal__CAP__0),
												GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, segasonic_Left_Shoe_DL_mesh_layer_2_mat_override_Metal__CAP__0),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Left_Sock),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 67, 50, 46, -19, 7, 159),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, segasonic_Left_Wing_DL_mesh_layer_4_mat_override_Metal__CAP__0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 0, -30, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, segasonic_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__CAP__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Right_Leg_skinned_mesh_layer_1_mat_override_Metal__CAP__0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, segasonic_Right_Leg_mesh_layer_1_mat_override_Metal__CAP__0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ASM(2, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__CAP__0),
													GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, segasonic_Right_Shoe_DL_mesh_layer_2_mat_override_Metal__CAP__0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Right_Sock),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 67, 50, -46, 19, -7, 159),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, segasonic_Right_Wing_DL_mesh_layer_4_mat_override_Metal__CAP__0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Spin),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Ball),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Spin_Dash),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_segasonic_Insta_Shield),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Half_Closed_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Closed_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Right_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Left[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Left_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Up_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Down[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Down_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Eyes_Dead_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Happy[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_Happy_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Shocked[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_Shocked_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Surprised[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_Surprised_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_No_Emotion[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_No_Emotion_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Happy[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_Happy_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Shocked[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_Shocked_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Surprised[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Mouth_Surprised_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Switch[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_mouth),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Side_Mouth_DL_mesh_layer_1_mat_override_Metal__CAP__0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Happy),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Shocked),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Switch_jump_segasonic_Mouth_Surprised),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Left_Hand_Thumbs_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, -78, 0, 0, segasonic_Left_Hand_Thumbs_Up_Switch_Option_Left_Hand_Thumbs_Up_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__CAP__0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal__CAP__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_2_mat_override_Metal__CAP__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal__CAP__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_4_mat_override_Metal__CAP__0),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_2_mat_override_Metal__CAP__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Left_Sock[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Sock_Switch_Option_Left_Sock_DL_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Right_Sock[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(2, geo_mario_hand_foot_scaler),
		GEO_SCALE(LAYER_OPAQUE, 65536),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Sock_Switch_Option_Right_Sock_DL_mesh_layer_1_mat_override_Metal__CAP__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Spin[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Spin_mesh_layer_1_mat_override_Metal__CAP__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Spin_mesh_layer_2_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Ball[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Ball_mesh_layer_1_mat_override_Metal__CAP__0),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Spin_Dash[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_SWITCH_CASE(0, geo_custom_spindash_states),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Spin_Dash_mesh_layer_1_mat_override_Metal__CAP__0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Insta_Shield[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Insta_Shield_mesh_layer_4_mat_override_Metal__CAP__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Switch_Option_Insta_Shield_mesh_layer_1_mat_override_Metal__CAP__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_ball_switch),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 40, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 62, 0, 0, segasonic_Torso_mesh_layer_1_mat_override_Metal__CAP__0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 61, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Eyes_Centered_DL_mesh_layer_1_mat_override_Metal__CAP__0),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Half_Closed),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Closed),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Right),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Left),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Up),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Down),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Eyes_Dead),
										GEO_CLOSE_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_mouth_side),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_mouth),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Mouth_Neutral_DL_mesh_layer_1_mat_override_Metal__CAP__0),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Happy),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Shocked),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Surprised),
													GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_No_Emotion),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Mouth_Switch),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 60, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, segasonic_Left_Arm_Color_mesh_layer_1_mat_override_Metal__CAP__0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Forearm_skinned_mesh_layer_1_mat_override_Metal__CAP__0),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Left_Forearm_mesh_layer_1_mat_override_Metal__CAP__0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_custom_hand_switch),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Hand_DL_mesh_layer_1_mat_override_Metal__CAP__0),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Left_Hand_Open),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Left_Hand_Thumbs_Up),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, -60, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, segasonic_Right_Arm_Color_mesh_layer_1_mat_override_Metal__CAP__0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Forearm_skinned_mesh_layer_1_mat_override_Metal__CAP__0),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, segasonic_Right_Forearm_mesh_layer_1_mat_override_Metal__CAP__0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_custom_hand_switch),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Hand_DL_mesh_layer_1_mat_override_Metal__CAP__0),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Right_Hand_Open),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Right_Hand_Peace),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Right_Hand_Cap),
												GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Right_Hand_Wing_Cap),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 0, 30, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, segasonic_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__CAP__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Leg_skinned_mesh_layer_1_mat_override_Metal__CAP__0),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, segasonic_Left_Leg_mesh_layer_1_mat_override_Metal__CAP__0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Shoe_DL_mesh_layer_1_mat_override_Metal__CAP__0),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Shoe_DL_mesh_layer_2_mat_override_Metal__CAP__0),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Left_Sock),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 67, 50, 46, -19, 7, 159),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Left_Wing_DL_mesh_layer_4_mat_override_Metal__CAP__0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 0, -30, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, segasonic_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__CAP__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Leg_skinned_mesh_layer_1_mat_override_Metal__CAP__0),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, segasonic_Right_Leg_mesh_layer_1_mat_override_Metal__CAP__0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ASM(2, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__CAP__0),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Shoe_DL_mesh_layer_2_mat_override_Metal__CAP__0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Right_Sock),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 67, 50, -46, 19, -7, 159),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_Right_Wing_DL_mesh_layer_4_mat_override_Metal__CAP__0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Spin),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Ball),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Spin_Dash),
			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_segasonic_Insta_Shield),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Mouth_Neutral_DL_mesh_layer_1_mat_override_Mouth_Frown__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Mouth_Neutral_DL_mesh_layer_1_mat_override_Mouth_Smile__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Mouth_Neutral_DL_mesh_layer_1_mat_override_Mouth_Grin__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Mouth_Neutral_DL_mesh_layer_1_mat_override_Mouth_Attacked__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout segasonic_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(99, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_OPAQUE_DECAL << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT_DECAL << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_ball_switch),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 40, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_move_mario_part_from_parent),
												GEO_ASM(0, geo_mario_tilt_torso),
												GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 62, 0, 0, segasonic_Torso_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 61, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_head_rotation),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Eyes_Centered_DL_mesh_layer_1),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, segasonic_Eyes_Half_Closed),
																	GEO_BRANCH(1, segasonic_Eyes_Closed),
																	GEO_BRANCH(1, segasonic_Eyes_Right),
																	GEO_BRANCH(1, segasonic_Eyes_Left),
																	GEO_BRANCH(1, segasonic_Eyes_Up),
																	GEO_BRANCH(1, segasonic_Eyes_Down),
																	GEO_BRANCH(1, segasonic_Eyes_Dead),
																GEO_CLOSE_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_mouth_side),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_SWITCH_CASE(0, geo_switch_mario_mouth),
																		GEO_OPEN_NODE(),
																			GEO_NODE_START(),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Mouth_Neutral_DL_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt1),
																			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt2),
																			GEO_BRANCH(1, segasonic_Mouth_Happy),
																			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt4),
																			GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Spin_Switch_opt0_Mouth_Side_Switch_opt0_Mouth_State_Switch_opt5),
																			GEO_BRANCH(1, segasonic_Mouth_Shocked),
																			GEO_BRANCH(1, segasonic_Mouth_Surprised),
																			GEO_BRANCH(1, segasonic_Mouth_No_Emotion),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, segasonic_Mouth_Switch),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 60, NULL),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, segasonic_Left_Arm_Color_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Left_Forearm_skinned_mesh_layer_1),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Left_Forearm_mesh_layer_1),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(1, geo_custom_hand_switch),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, NULL),
																			GEO_OPEN_NODE(),
																				GEO_ASM(1, geo_mario_hand_foot_scaler),
																				GEO_SCALE(LAYER_FORCE, 65536),
																				GEO_OPEN_NODE(),
																					GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Left_Hand_DL_mesh_layer_1),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, segasonic_Left_Hand_Open),
																		GEO_BRANCH(1, segasonic_Left_Hand_Thumbs_Up),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, -60, NULL),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, segasonic_Right_Arm_Color_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Right_Forearm_skinned_mesh_layer_1),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, segasonic_Right_Forearm_mesh_layer_1),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(0, geo_custom_hand_switch),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, NULL),
																			GEO_OPEN_NODE(),
																				GEO_ASM(0, geo_mario_hand_foot_scaler),
																				GEO_SCALE(LAYER_FORCE, 65536),
																				GEO_OPEN_NODE(),
																					GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Right_Hand_DL_mesh_layer_1),
																				GEO_CLOSE_NODE(),
																				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, segasonic_Right_Hand_Open),
																		GEO_BRANCH(1, segasonic_Right_Hand_Peace),
																		GEO_BRANCH(1, segasonic_Right_Hand_Cap),
																		GEO_BRANCH(1, segasonic_Right_Hand_Wing_Cap),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 0, 30, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, segasonic_Left_Thigh_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Left_Leg_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, segasonic_Left_Leg_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Left_Shoe_DL_mesh_layer_1),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, segasonic_Left_Shoe_DL_mesh_layer_2),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, segasonic_Left_Sock),
																GEO_CLOSE_NODE(),
																GEO_TRANSLATE_ROTATE(LAYER_FORCE, 67, 50, 46, -19, 7, 159),
																GEO_OPEN_NODE(),
																	GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
																	GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_ALPHA, segasonic_Left_Wing_DL_mesh_layer_4),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 0, -30, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, segasonic_Right_Thigh_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Right_Leg_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, segasonic_Right_Leg_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ASM(2, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_Right_Shoe_DL_mesh_layer_1),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, segasonic_Right_Shoe_DL_mesh_layer_2),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, segasonic_Right_Sock),
																GEO_CLOSE_NODE(),
																GEO_TRANSLATE_ROTATE(LAYER_FORCE, 67, 50, -46, 19, -7, 159),
																GEO_OPEN_NODE(),
																	GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
																	GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_ALPHA, segasonic_Right_Wing_DL_mesh_layer_4),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, segasonic_Spin),
									GEO_BRANCH(1, segasonic_Ball),
									GEO_BRANCH(1, segasonic_Spin_Dash),
									GEO_BRANCH(1, segasonic_Insta_Shield),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt1),
							GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt2),
							GEO_BRANCH(1, segasonic_B_LoD_Switch_opt0_Cap_State_Switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_OPAQUE_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, segasonic_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, segasonic_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, segasonic_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, segasonic_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
